version: '3'
services:
  redis:
    image: redis:latest
    container_name: crazy-ms-redis
    networks:
      - crazy-network
    ports:
      - '6379:6379'
    volumes:
      - cacheRedis:/data

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: crazy-ms-api-gateway
    ports:
      - 5000:5000
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: >
      bash -c "
      pnpm run dev;"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: crazy-ms-auth-service  # user service
    ports:
      - 3010:3010
    networks:
      - crazy-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: >
      bash -c "
      pnpm run dev;"

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: crazy-ms-product-service
    ports:
      - 3020:3020
    volumes:
      - ./product-service:/app
      - /app/node_modules
    networks:
      - crazy-network
    env_file:
      - ./.env
    command: >
      bash -c "
      pnpm run dev;"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: crazy-ms-order-service
    ports:
      - 3030:3030
    networks:
      - crazy-network
    volumes:
      - ./order-service:/app
      - /app/node_modules
    env_file:
      - ./.env
    command: >
      bash -c "
      pnpm run dev;"

volumes:
  cacheRedis:

networks:
  crazy-network:
    driver: bridge
